#Hayat hakkında güçlü alıntılar ve sözler

quotes_teletips = [
"Herkes için aşk, hiç kimse için nefret.", 
"Kendin olarak dünyayı değiştir.",
"Her an yeni bir başlangıçtır..",
"Never regret anything that made you smile.",
"Hayallerle değil anılarla öl.",
"Süremiz dolmadan ilham vermek istiyor.",
"Hayal edebileceğin her şey gerçek..",
"Basitlik en gelişmişliktir.",
"Whatever you do, do it well.",
"Ne düşündüğümüzü, biz..",
"Tüm sınırlamalar kendi kendine dayatılan.",
"Zor zamanlar asla sürmez ama sert insanlar yapar..",
"Sorunlar dur işaretleri değildir, yönergelerdir.",
"Başlamak için yeterli cesaretiniz ve bitirmek için yeterli yüreğiniz var.",
"Sana katılıyorum ama o zaman ikimiz de yanılıyor oluruz..",
"Oh, bulabileceğin şeyler, eğer geride kalmazsan..",
"Önceliklerinizi belirleyin ve bunlara odaklanın.",
"O kadar iyi ol ki seni görmezden gelemezler..",
"Dün yarın demiştin. Hemen yap.",
"Kolay olmasına ihtiyacım yok, buna değecek..",
"Duygularının zekanı alt etmene asla izin verme.",
"Hiçbir şey sonsuza dek sürmez ama en azından bu anılara sahipiz..",
"Kusurlarının bir lütuf olduğunu bilmiyor musun??",
"Gerçeklik yanlıştır, hayaller gerçektir.",
"Yaşamak çok büyük bir macera olacak..",
"Birinin bulutunda gökkuşağı olmaya çalış..",
"Sıkı çalışmanın yerini tutamaz..",
"Zihninizi tüketen şey hayatınızı kontrol eder.",
"Büyüklük için çabalayın.",
"Ve yine de, yükseliyorum.",
"Doğru olanı yapmanın zamanı her zaman doğrudur..",
"Sevdiğin şeyin güzelliği yaptığın şey olsun..",
"Seçimleriniz umutlarınızı yansıtsın, korkularınızı değil..",
"Mutlu bir ruh zalim bir dünya için en iyi kalkandır..",
"Beyaz her zaman açık değildir ve siyah her zaman karanlık değildir.",
"Mutluluk kendimize bağlıdır.",
"Yaralarını bilgeliğe çevir..",
"Oyunu değiştir, oyunun seni değiştirmesine izin verme.",
"Acıttı çünkü önemliydi..",
"Hatırlayacağım ve iyileşeceğim, affetmeyeceğim ve unutmayacağım.",
"Hayatın anlamı hayata anlam vermektir.",
"Kelimeler başarısız olduğunda, müzik konuşur.",
"Olduğun muhteşem karmaşayı kucakla.",
"Kaybedecek bir şeyim yok ama kazanacak bir şeyim var.."
]
